### PR TITLE
Split codes for micro-ros lib and example

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Closes https://github.com/micro-ROS/micro_ros_nuttx_app/issues/20

### CODE REVIEW

**Comment by pablogs9** [comment]
Could we rename `example_app` to `microros_example_app`?

**Comment by pablogs9** [comment]
I guess that [this line](https://github.com/micro-ROS/micro_ros_nuttx_app/blob/b72e4503733cb4fbc468fa26b9668c43db7b4d42/.github/workflows/ci.yml#L41) of the CI should be modified to copy both folders correctly? Would you mind @Barry-Xu-2018?

**Comment by Barry-Xu-2018** [comment]
> I guess that [this line](https://github.com/micro-ROS/micro_ros_nuttx_app/blob/b72e4503733cb4fbc468fa26b9668c43db7b4d42/.github/workflows/ci.yml#L41) of the CI should be modified to copy both folders correctly? Would you mind @Barry-Xu-2018?

No need. 
For my understanding, `repo` at [this line](https://github.com/micro-ROS/micro_ros_nuttx_app/blob/b72e4503733cb4fbc468fa26b9668c43db7b4d42/.github/workflows/ci.yml#L41) is the directory cloned from the repository.  Right ?

The below step need not be changed in README.
```
git clone https://github.com/micro-ROS/micro_ros_nuttx_app apps/microros
```
But you should add the below line in CI
```
kconfig-tweak --enable CONFIG_MICROROS_EXAMPLE
```

**Comment by pablogs9** [comment]
You are right.

CI updated

**Pull request merged**
